"""Protocol definition for TOM backends (Desktop, XMLA, Mock)."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TomBackendProtocol(Protocol):
    """Defines the contract all TOM-compatible backends must satisfy."""

    # --- Connection ---
    def connect(self, **kwargs: Any) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...

    # --- Model info ---
    def model_info(self) -> dict[str, Any]: ...
    def table_list(self) -> list[dict[str, Any]]: ...
    def column_list(self, table: str | None = None) -> list[dict[str, Any]]: ...
    def relationship_list(self) -> list[dict[str, Any]]: ...

    # --- Measures ---
    def measure_list(self, table: str | None = None) -> list[dict[str, Any]]: ...
    def measure_add(
        self, table: str, name: str, expression: str, **kwargs: Any
    ) -> dict[str, Any]: ...
    def measure_update(self, table: str, name: str, **kwargs: Any) -> dict[str, Any]: ...
    def measure_delete(self, table: str, name: str) -> None: ...

    # --- Tables ---
    def table_add(self, name: str, **kwargs: Any) -> dict[str, Any]: ...
    def table_delete(self, name: str) -> None: ...

    # --- Columns ---
    def column_add(
        self, table: str, name: str, data_type: str, **kwargs: Any
    ) -> dict[str, Any]: ...
    def column_delete(self, table: str, name: str) -> None: ...

    # --- Relationships ---
    def relationship_add(
        self, from_table: str, from_column: str, to_table: str, to_column: str, **kwargs: Any
    ) -> dict[str, Any]: ...

    # --- DAX ---
    def dax_query(self, expression: str) -> list[dict[str, Any]]: ...
    def dax_validate(self, expression: str) -> dict[str, Any]: ...

    # --- TMDL ---
    def tmdl_export(self, path: str) -> None: ...
    def tmdl_import(self, path: str) -> None: ...

    # NOTE: Extended structural operations — partitions, roles, calculation
    # groups, and hierarchy *writes* — are intentionally NOT part of this core
    # contract because not every backend implements them (the read-only `rest`
    # backend and the AMO-based `xmla` backend each support a different subset).
    # Callers that need them should feature-detect with ``hasattr`` rather than
    # assume the method exists. The mock/file/fabric backends implement the full
    # extended surface; see ``ExtendedTomBackendProtocol`` for that wider shape.


@runtime_checkable
class ExtendedTomBackendProtocol(TomBackendProtocol, Protocol):
    """The full structural surface implemented by the in-memory/TMDL backends.

    ``mock``, ``file`` and ``fabric`` satisfy this; ``xmla``/``rest`` satisfy only
    the narrower :class:`TomBackendProtocol`. Kept separate so the conformance
    tests can assert each backend against the contract it actually fulfils
    instead of forcing every backend to implement operations it cannot.
    """

    # --- Hierarchies ---
    def hierarchy_list(self, table: str | None = None) -> list[dict[str, Any]]: ...
    def hierarchy_add(
        self, table: str, name: str, levels: list[dict[str, Any]]
    ) -> dict[str, Any]: ...
    def hierarchy_delete(self, table: str, name: str) -> None: ...

    # --- Calculation groups ---
    def calc_group_list(self) -> list[dict[str, Any]]: ...
    def calc_group_add(self, name: str, precedence: int = 0) -> dict[str, Any]: ...
    def calc_item_add(
        self, group_table: str, name: str, expression: str, ordinal: int = 0
    ) -> dict[str, Any]: ...
    def calc_item_delete(self, group_table: str, name: str) -> None: ...

    # --- RLS roles ---
    def role_list(self) -> list[dict[str, Any]]: ...
    def role_add(self, name: str, table: str, filter_expression: str) -> dict[str, Any]: ...
    def role_delete(self, name: str) -> None: ...

    # --- Partitions ---
    def partition_list(self, table: str | None = None) -> list[dict[str, Any]]: ...
    def partition_add(self, table: str, name: str, query: str) -> dict[str, Any]: ...
    def partition_delete(self, table: str, name: str) -> None: ...
    def partition_refresh(self, table: str, name: str) -> dict[str, Any]: ...
