"""Protocol definition for TOM backends (Desktop, XMLA, Mock)."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TomBackendProtocol(Protocol):
    """Defines the contract all TOM-compatible backends must satisfy."""

    # --- Connection ---
    def connect(self, **kwargs: Any) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...

    # --- Model info ---
    def model_info(self) -> dict[str, Any]: ...
    def table_list(self) -> list[dict[str, Any]]: ...
    def column_list(self, table: str | None = None) -> list[dict[str, Any]]: ...
    def relationship_list(self) -> list[dict[str, Any]]: ...

    # --- Measures ---
    def measure_list(self, table: str | None = None) -> list[dict[str, Any]]: ...
    def measure_add(self, table: str, name: str, expression: str, **kwargs: Any) -> dict[str, Any]: ...
    def measure_update(self, table: str, name: str, **kwargs: Any) -> dict[str, Any]: ...
    def measure_delete(self, table: str, name: str) -> None: ...

    # --- Tables ---
    def table_add(self, name: str, **kwargs: Any) -> dict[str, Any]: ...
    def table_delete(self, name: str) -> None: ...

    # --- Columns ---
    def column_add(self, table: str, name: str, data_type: str, **kwargs: Any) -> dict[str, Any]: ...
    def column_delete(self, table: str, name: str) -> None: ...

    # --- Relationships ---
    def relationship_add(self, from_table: str, from_column: str, to_table: str, to_column: str, **kwargs: Any) -> dict[str, Any]: ...

    # --- DAX ---
    def dax_query(self, expression: str) -> list[dict[str, Any]]: ...
    def dax_validate(self, expression: str) -> dict[str, Any]: ...

    # --- TMDL ---
    def tmdl_export(self, path: str) -> None: ...
    def tmdl_import(self, path: str) -> None: ...
